from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS


embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

available_items = [
    "Mazanec 400g",
    "Mazanec s rozinkami sypaný mandlemi 400g",
    "Mazanec máslový 400g",
    "Vánočka s rozinkami 200g",
    "Vánočka 400g",
    "Vánočka máslová rozinková mandlová 600g",
    "Vánočka s rozinkami a mandlemi 5 ks á 400g 2000g",
    "Špička s náplní makovou 2ks á 110g",
    "Špička s náplní makovou a tvarohovou 2ks á110g",
    "Chléb konzumní s kmínem 1200g",
    "Chléb konzumní s kmínem 500g - předpečený BIDVEST",
    "Chléb s kmínem Šumava 6x570g 3420gBK",
    "Zelňák 30g - předpečený",
    "Rohlík 43g",
    "Raženka bez posyp. 30x60g",
    "Bábovky MIX (3ks mramorová 400g, 3ks šlehaná 400g) 2400g",
    "Klimentovský chléb (jedlá etiketa) 800g",
    "Tesco Finest Vícezrnný chléb s quinoou 500g",
    "Banketka 20g",
    "Bageta 150g",
    "Bulka 50g",
    "Bulka velká 60g",
    "Houska 43g",
    "Houska velká 86g",
    "Rohlík 43g",
    "Rohlík velký 60g",
    "Veka 380g",
    "Bulka se slaninou 75g",
    "Pizza houska 85g",
    "Rohlík se slaninou 55g",
    "Rohlík PIZZA 50g",
    "Houska švédská rustikální 80g",
    "Rohlík špalda 80g",
    "Dalamánek sypaný 150g",
    "Kostka tmavá 60g",
    "Kostka tmavá 43g",
    "Rohlík kornový 60g",
    "Bulka dýňová 90g",
    "Rohlík RUSTAL 60g",
    "Rohlík FINSKÝ 60g",
    "Rohlík ZLATÝ 60g",
    "Chléb domácí 930g",
    "Chléb domácí kulatý 930g",
    "Chléb malý 500g",
    "Chléb na polévku 400g",
    "Dalamánek chlebový 85g",
    "Chléb pivní 500g",
    "Chléb královský 700g",
    "Chléb kořenový 350g",
    "Chléb kořenový s cibulí 350g",
    "Dukátové buchtičky 1000g",
    "Jidáše 86g",
    "Loupák 70g",
    "Loupák GASTRO 24g",
    "Buchty 65g",
    "Buchty GASTRO 58g",
    "Chodský koláč 1130g",
    "Koláč hřeben 75g",
    "Koláč kulatý 80g",
    "Koláč kulatý malý 30g",
    "Koláč šáteček 75g",
    "Koláč tříbarevný 80g",
    "Koláč vázaný GASTRO 30g",
    "Koláč velký 130g",
    "Koláč větší vázaný 100g",
    "Koláč větší šáteček 100g",
    "Koláč švýcarka 120g",
    "Koláč skořicový 85g",
    "Koláček kulatý 18g",
    "Loupák plněný 75g",
    "Metýnka 150g",
    "GASTRO 2000g",
    "Závin 400g",
    "Skořicový cop 50g",
    "Cop GASTRO 30g",
    "Skořicový cop čoko 55g",
    "Cop čoko GASTRO 40g",
    "Kobliha 50g",
    "Kobliha GASTRO 35g",
    "Kobliha čoko GASTRO 43g",
    "Kobliha PUDING 60g",
    "Taštička povidlová 70g",
    "Taštička jablečná 70g",
    "Taštička nugátová 70g",
    "Vdolek bavorský 60g",
    "Koláč kulatý DIA 80g",
    "Koláč šáteček DIA 80g",
    "Buchty DIA 65g",
    "Metýnka DIA 150g",
    "Chlebíček biskupský 600g",
    "Perník 100g",
    "Makovec 100g",
    "Arašídový řez 100g",
    "Listové ouško 45g",
    "Trojhránek polomáčený 70g",
    "GASTRO 920g",
    "Cereální linecký řez 100g",
    "Trojhránek linecký cereální 110g",
    "Josefínky 60g",
    "Biskupský chlebíček 200g",
    "Beránek velikonoční biskupský 500g",
    "Koláček balený vázaný(tácek) 120g",
    "Koláček balený šáteček(tácek) 120g",
    "Koláček balený kulatý (tácek) -malé bal. 125g",
    "Mazanec 400g",
    "Vánočka arašídová 400g",
    "Vánočka DIA 400g",
    "Vánočka mandlová 400g",
    "Slunečnicový chléb 400g",
    "Kornový chléb 400g",
    "Chutný preclík 100g",
    "Chutný preclík celozrnný 100g",
    "Chutný preclík velký - 4ks (110g",
    "Veka sváteční – krájená 380g",
    "Bábovka 450g",
    "Bábovka DIA 450g",
    "Celozrnná pochoutka 60g",
    "Bělohradský chléb 930g",
    "Bělohradský chléb – malý 500g",
    "Vícezrnná veka – krájená 300g"
]

available_items_db = FAISS.from_texts(available_items, embeddings)